import type { ShipConfig } from '../config.js';

// JSON.stringify gives safe quoting/escaping for values interpolated into generated code.
function q(value: string): string {
  return JSON.stringify(value);
}

/** capacitor.config.ts for the user's app. */
export function capacitorConfig(cfg: ShipConfig): string {
  const deepLink =
    cfg.deepLinkScheme === undefined
      ? ''
      : `
// Deep links (${cfg.deepLinkScheme}://): handle opens with the Capacitor App plugin ('appUrlOpen' event)
// and register the scheme in the native projects — iOS Info.plist CFBundleURLTypes,
// Android intent-filter. See https://capacitorjs.com/docs/apis/app`;
  const server =
    cfg.devUrl === undefined
      ? ''
      : `
  // Dev-only: loads the app from the Vite dev server. Remove \`server\` for release builds.
  server: {
    url: ${q(cfg.devUrl)},${cfg.devUrl.startsWith('http://') ? '\n    cleartext: true,' : ''}
  },`;
  return `import type { CapacitorConfig } from '@capacitor/cli';
${deepLink}
const config: CapacitorConfig = {
  appId: ${q(cfg.appId)},
  appName: ${q(cfg.appName)},
  webDir: ${q(cfg.webDir)},${server}
};

export default config;
`;
}

/** electron/main.mjs — Electron main process for the Microsoft Store shell. */
export function electronMain(cfg: ShipConfig): string {
  const width = cfg.electron?.width ?? 1280;
  const height = cfg.electron?.height ?? 800;
  // loadFile paths resolve relative to the app root, so this works both unpacked and inside app.asar.
  const loadFile = `win.loadFile(join(${q(cfg.webDir)}, 'index.html'));`;
  const load =
    cfg.devUrl === undefined
      ? `  ${loadFile}`
      : `  if (process.env.ELECTRON_DEV === '1') {
    win.loadURL(${q(cfg.devUrl)});
  } else {
    ${loadFile}
  }`;
  return `// Generated by kitbash-ship — Electron main process.
import { app, BrowserWindow } from 'electron';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

function createWindow() {
  const win = new BrowserWindow({
    width: ${width},
    height: ${height},
    webPreferences: {
      contextIsolation: true,
      // ESM (.mjs) preload scripts require an unsandboxed renderer.
      sandbox: false,
      preload: join(here, 'preload.mjs'),
    },
  });
${load}
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});
`;
}

/** electron/preload.mjs — placeholder renderer API surface. */
export function electronPreload(): string {
  return `// Generated by kitbash-ship — preload runs with Node access.
import { contextBridge } from 'electron';

// Placeholder surface: exposes nothing yet. Add methods here instead of enabling nodeIntegration.
contextBridge.exposeInMainWorld('kitbash', {});
`;
}

/** electron-builder.json — MSIX (appx) packaging config. */
export function electronBuilderConfig(cfg: ShipConfig): string {
  const config = {
    appId: cfg.appId,
    productName: cfg.appName,
    // Keep packaging output out of the web build directory.
    directories: { output: 'dist-electron' },
    files: [`${cfg.webDir}/**/*`, 'electron/**/*'],
    win: { target: ['appx'] },
    appx: {
      // These MUST match your Partner Center app identity exactly, or the Store upload is rejected.
      identityName: cfg.windows?.identityName ?? cfg.appId,
      publisherDisplayName: cfg.windows?.publisherDisplayName ?? cfg.appName,
      publisher: cfg.windows?.publisher ?? `CN=${cfg.appName}`,
    },
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

/** public/manifest.webmanifest — PWA manifest. */
export function webManifest(cfg: ShipConfig): string {
  const manifest = {
    name: cfg.appName,
    short_name: cfg.appName,
    id: '/',
    start_url: '/',
    display: 'standalone',
    theme_color: '#ffffff',
    background_color: '#ffffff',
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/** public/sw.js — no-op cache-shell service worker (presence makes the app installable). */
export function serviceWorker(): string {
  return `// Generated by kitbash-ship — minimal no-op service worker shell.
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('fetch', () => {
  // Intentionally empty: requests fall through to the network. Add caching here when needed.
});
`;
}

/** src/kitbash-sw.ts — registration snippet for the user's app entry. */
export function swRegister(): string {
  return `// Generated by kitbash-ship — call registerSW() once from your app entry (e.g. main.tsx).
export function registerSW(): void {
  if (!('serviceWorker' in navigator)) return;
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch((error: unknown) => {
      console.warn('[kitbash] service worker registration failed', error);
    });
  });
}
`;
}
